language: node_js
node_js:
  - "7"

# safelist
branches:
  only:
  - master

env:
  - "AUTH=false"
  - "AUTH=true USER=test PASSWORD=secret"
  
install:
  - npm install
  
before_script:
  - npm start
  - npm run lint
  
script:
  - npm test